### ISSUE TITLE
32-bit OS compatibility

### ISSUE THREAD

**Issue by upward4** [ProtonMail/go-rfc5322#2]
Is compatibility with 32-bit OSes technically achievable? If so, what are the current showstoppers?

**Comment by jameshoulahan** [comment]
Technically, yes. The issue is that the golang code generated by ANTLR4 isn't 32-bit compatible. The [issue](https://github.com/antlr/antlr4/issues/2433) has been around for a while. We could probably hack the generated code to make it 32-bit compatible but as Bridge no longer supports 32-bit anyway, we didn't bother doing that yet.

If you want to build it yourself for 32-bit, fork this repo, apply the sed hack (from a comment in the linked issue), add a replace directive for this repo with your own fork in bridge's `go.mod`, and it *should* work on 32-bit (untested).

**Comment by upward4** [comment]
> as Bridge no longer supports 32-bit anyway, we didn't bother doing that yet.

But the exact reason why bridge doesn't support 32-bit is that ANTLR4 isn't 32-bit compatible, right? Or are you saying there were other considerations when choosing to drop support for 32-bit in the bridge?

**Comment by jameshoulahan** [comment]
Sorry for just getting back to this now.

The original reason we considered dropping 32-bit support came from unrecoverable errors in etcd-io's `bbolt` database affecting all our target OSes when running 32-bit builds. We [reported](https://github.com/etcd-io/bbolt/issues/202) the issue upstream early last year but that report got no traction. Our product team made the decision to only support 64-bit from around that point on because running 32-bit builds was no longer considered stable and there wasn't anything we could realistically do; it also aligned with the general trend of OSes at the time.

And yes, now that we wrote our RFC5322 parser using ANTLR4, we have a second factor to take into account.
